#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/search_engine?useSSL=false&serverTimezone=UTC
#spring.datasource.username=valgall
#spring.datasource.password=Gorila123
#spring.jpa.hibernate.ddl-auto=update
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/search_engine?useSSL=false&serverTimezone=UTC
    username: valgall
    password: Gorila123
  jpa:
    hibernate:
      ddl-auto: none

someParameter:
  value: 5469
available-sites:
  xyz: 123;
  sites:
    - url: http://www.playback.ru
      name: "playback"
    - url: https://volochek.life
      name: "?????????????? ?????? ?????? ???????"
    - url: http://radiomv.ru
      name: "????????????????"
    - url: https://dimonvideo.ru
      name: "DimonVideo"
    - url: https://www.svetlovka.ru
      name: "?????????"
    - url: https://ipfran.ru
      name: "??? ???"


