spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/search_engine?useSSL=false&serverTimezone=UTC
    username: valgall
    password: Gorila123
  jpa:
    hibernate:
      ddl-auto: none
      dialect: DB2Dialect
available-sites:
  sites:
    - url: https://nikoartgallery.com
      name: "Галерея Никогосяна"
    - url: http://www.playback.ru
      name: "playback"
    - url: https://volochek.life
      name: "ВОЛОЧЕК"
    - url: http://radiomv.ru
      name: "РАДИОМИЛИЦИЯ"
    - url: https://dimonvideo.ru
      name: "DimonVideo"
    - url: https://www.svetlovka.ru
      name: "СВЕЛОВКА"
    - url: https://ipfran.ru
      name: "ИП ФАН"


